name: Build SteamConfigEditor

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore SteamConfigEditor.sln

    - name: Build solution
      run: dotnet build SteamConfigEditor.sln --configuration Release --no-restore

    - name: Upload compiled EXE
      uses: actions/upload-artifact@v4
      with:
        name: SteamConfigEditor-exe
        path: SteamConfigEditor/bin/Release/net6.0-windows/SteamConfigEditor.exe
